config/routes.rb
Rails.application.routes.draw do

  unauthenticated :trader do
    root to: 'homepage#index', as: :unauthenticated_root
  end

  authenticated :trader do
    root to: 'dashboard#index', as: :authenticated_root
    get '/homepage' => 'homepage#index', as: :homepage
  end

  devise_scope :trader do
    root to: 'devise/sessions#new'
  end

  resources :transactions
  
  # get 'buy', to: 'transactions#new'
  # post 'buy', to: 'transactions#new'

  get 'search', to: 'search#index' 
  get 'portfolio', to: 'dashboard#portfolio'
  get 'pending', to: 'dashboard#pending'
 
# <<<<<<< HEAD
#   get 'portfolio', to: 'pages#portfolio'
 

#   root 'pages#home'
# =======
  
  
  resources :transactions
  resources :stocks_traders
  resources :stocks do
    get 'buy', to: 'transactions#new'
    post 'buy', to: 'transactions#new'
    # resources :transactions
  end
  devise_for :traders
  resources :traders  
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :set_client

  def index
    @stocks = Stock.all
    @microsoft = @client.quote('MSFT').latest_price
    # @logo = @client.logo('MSFT')
    @top_ten = @client.stock_market_list(:mostactive)
    @symbols = @client.ref_data_symbols()

    # @code = params[:code]
    # @stock = Stock.find(paramss[:id])

    # @company_stock = @client.quote(@stock.code)
    @companies = []

    @stocks.each do |stock|
      if stock.code != nil
        if @companies.length < 20
          @companies.push(@client.quote(stock.code))
        end
      end
    end

    if current_trader.admin
      @transactions = Transaction.all
    else
      @transactions = Transaction.where(trader_id: current_trader.id)
    end

  end

  def portfolio 
    @top_ten = @client.stock_market_list(:mostactive)
    @microsoft = @client.quote('MSFT').latest_price
    @current_stocks = current_trader.stocks
    @owned_stocks = Portfolio.where(trader_id: current_trader.id).where("volume > 0").collect do |x|
      {
        trader_id: Trader.find(x.trader_id).email ,
        name: Stock.find(x.stock_id).name,
        volume: x.volume,
        price: @client.quote(Stock.find(x.stock_id).code).latest_price,
        code: Stock.find(x.stock_id).code,
        value: x.volume * @client.quote(Stock.find(x.stock_id).code).latest_price
      }
    end
    # @owned_stocks = StocksTrader.where(trader_id: current_trader.id).where("volume > 0")
  end

  def pending
    @traders = Trader.where(approved_boolean: false)
  end

  private

  def set_client
    @client = Iex.client
    # @stock = Stock.find(params[:id])
  end
end

app/views/dashboard/_nav.html.erb
<div class="dashboard-nav">
  <div class="top">
    <%= link_to image_tag("/logo3.png"), homepage_path, class:"image" %>
    <div>
      <span class="material-symbols-sharp close">close</span>
    </div>
  </div>
  
  <div class="sidebar">
    <a href="/" class="active">
      <span class="material-symbols-sharp">dashboard</span> 
      <h3>Dashboard</h3>
    </a>
    <a href="/stocks">
      <span class="material-symbols-sharp">shopping_cart</span>
      <h3>Buy Stocks</h3>
    </a>
    <a href="/portfolio">
      <span class="material-symbols-sharp">point_of_sale</span>
      <h3>Portfolio</h3>
    </a>
    <a href="/transactions">
      <span class="material-symbols-sharp">point_of_sale</span>
      <h3>Transactions</h3>
    </a>
    <a href="<% edit_trader_registration_path %>">
      <span class="material-symbols-sharp">settings</span>
      <h3>Settings</h3>
    </a>
    <a data-turbo-method="delete" class="logout" href="/traders/sign_out">
      <span class="material-symbols-sharp">logout</span>
      <h3>Log Out</h3>
    </a>
  </div>
</div>

app/views/dashboard/asdasd.html.erb
<p> Hello <%= current_trader.first_name <%= current_trader.last_name %>!</p> %>
      <p>You are logged in.</p>
      <% if !current_trader.admin %>
          <p>You are a trader.</p>
          <p><%= link_to "Portfolio", portfolio_path %></p>
      <% else %>
          <p><strong>You are an admin.</strong></p>
          <p><%= link_to "Portfolio", portfolio_path %></p>
          <p>There are <%= Trader.count %> in the system.</p>
          <p><%= link_to "All Users", traders_path %></p>
          <p><%= link_to "Pending Traders", pending_path %></p>
      <%end %>

app/views/dashboard/index.html.erb
<% if current_trader %>
  <div class="dashboard">
    <%= render 'dashboard/nav' %>
    <div class="dash-home">
      <div>
          <h1 class="dash-welcome"> Welcome, <%= current_trader.first_name%> <%= current_trader.last_name%>!<span class="text-muted"><%= current_trader.admin ? "(Admin)" : "(Trader)" %></span></h1>
          <div class="dash-balance">
            <div class="cash"><%= number_to_currency(current_trader.cash) %></div>
          <h3>Available Balance</h3>
        </div>
      </div>
     

  <div class="trending-stocks">
        <h2>Trending Stocks</h2>
        <ul class="stocks">
          <% @top_ten.each do |company| %>
            <div class="company-details">
              <div class="company-name">
                <span><%= company.company_name %></span>
                <strong><%= company.symbol %></strong>
              </div>
              <div class="company-price">
                <strong>$<%= company.latest_price %></strong>
                <% if company.change >= 0 %>
                  <strong class="green"><i class="fa-solid fa-arrow-trend-up"></i> <%= company.change_percent_s %></strong>
                <% else %>
                  <strong class="red"><i class="fa-solid fa-arrow-trend-down"></i> <%= company.change_percent_s %></strong>
                <% end %>
              </div>
            </div>
          <% end %>
        </ul>
      </div>

      <div class="all-stocks">
        <h2>All Stocks</h2>
        <div class="stocks-description">
            <div >Name</div>
            <div>Price</div>
            <div>Change</div>
        </div>
  
        <div class="stocks-wrapper">
          <% @companies.each do |company| %>
            <% if company.company_name != nil %>
              <div class="stock">
                  <div><%= company.company_name %></div>
                  <div class="stock-price">$<%= company.latest_price %></div>
                  <div class="<%= company.change && (company.change >= 0) ? "success" : "danger" %> stock-percent"><%= company.change_percent_s ? company.change_percent_s : '0.00%' %></div>
                  <div class="transac">
                    <button class="buy">Buy</button>
                    <button class="sell">Sell</button>
                  </div>
              </div>
            <% end %> 
          <% end %> 
        </div>  
      </div>
    </div>
    <div class="dash-right">
      <h2><%= !current_trader.admin ? 'Transactions' : 'Users transaction' %></h2>

      <div id="transactions" class="transaction">
        <% @transactions.each do |transaction| %>
          <p>Created At: <%= transaction.created_at %></p>
          <%= render transaction %>
          <br>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<%# <% if !current_trader.admin %>
 <%# <p>You are a trader.</p>
<%#<% else %>
 <%#   <p><strong>You are an admin.</strong></p>
 <%#   <p>There are <%= Trader.count %> <%#in the system.</p>
  <%#  <p><%= link_to "All Users", traders_path %><%#</p>
<%# <%end %>

      <%# <%= link_to "Search", search_path %>

app/views/dashboard/pending.html.erb
<% if current_trader.admin %>
    <h1>Pending</h1>
    <% @traders.each do |trader| %>
    <ul>
     <li>
      <p>
        <strong>ID:</strong>
        <%= trader.id %>
      </p>

      <p>
        <strong>Name:</strong>
        <%= trader.first_name %> <%= trader.last_name %>
      </p>

      </li>
      <%= link_to "Show trader", trader %>
    </ul>

    <% end %>
    <p><%= link_to "Back to Home", root_path %></p>

<% else %>
    <p>Hello <%= current_trader.first_name %> <%= current_trader.last_name %>! You are a basic trader. You cannot access this page.
    <p><%= link_to "Back to Home", root_path %></p>
    <%= link_to "Sign Out", destroy_trader_session_path, 'data-turbo-method': :delete %>
<%end%>

app/views/dashboard/portfolio.html.erb
<div class="portfolio">
    <div class="portfolio-nav">
        <div class="top">
            <%= link_to image_tag("/logo3.png"), homepage_path, class:"image" %>
            <div>
            <span class="material-symbols-sharp close">close</span>
            </div>
        </div>
        
        <div class="sidebar">
            <a href="/" >
                <span class="material-symbols-sharp">dashboard</span> 
                <h3>Dashboard</h3>
            </a>
            <a href="/stocks">
                <span class="material-symbols-sharp">shopping_cart</span>
                <h3>Buy Stocks</h3>
            </a>
            <a href="/portfolio" class="active">
                <span class="material-symbols-sharp">account_circle</span>
                <h3>Portfolio</h3>
            </a>
            <a href="/transactions">
                <span class="material-symbols-sharp">point_of_sale</span>
                <h3>Transactions</h3>
            </a>
            <a href="<% edit_trader_registration_path %>">
                <span class="material-symbols-sharp">settings</span>
                <h3>Settings</h3>
            </a>
            <% if current_trader.admin %>
            <a href="/traders">
                <span class="material-symbols-sharp">group</span>
                <h3>All Users</h3>
            </a>
            <% end %>
            <a data-turbo-method="delete" class="logout" href="/traders/sign_out">
                <span class="material-symbols-sharp">logout</span>
                <h3>Log Out</h3>
            </a>
        </div>
    </div>
    <div>
        <h1><%= current_trader.first_name %>'s Portfolio</h1>
        <ul>
            <% @owned_stocks.each do |stock|%>
                <li>
                    <p>Stock Name: <%= stock[:name]%>(<%= stock[:code]%>)</p>
                    <p>Total Shares: <%= stock[:volume]%></p>
                    <p>Stock Price: <%= stock[:price]%></p>
                    <p>Current Value: <%= stock[:value]%></p>
                    <br/>
                </li>
            <%end%> 
        </ul>
    </div>
</div>