config/routes.rb
Rails.application.routes.draw do

  unauthenticated :trader do
    root to: 'homepage#index', as: :unauthenticated_root
  end

  authenticated :trader do
    root to: 'dashboard#index', as: :authenticated_root
    get '/homepage' => 'homepage#index', as: :homepage
  end

  devise_scope :trader do
    root to: 'devise/sessions#new'
  end

  resources :transactions
  
  # get 'buy', to: 'transactions#new'
  # post 'buy', to: 'transactions#new'

  get 'search', to: 'search#index' 
  get 'portfolio', to: 'dashboard#portfolio'
  get 'pending', to: 'dashboard#pending'
 
# <<<<<<< HEAD
#   get 'portfolio', to: 'pages#portfolio'
 

#   root 'pages#home'
# =======
  
  
  resources :transactions
  resources :stocks_traders
  resources :stocks do
    get 'buy', to: 'transactions#new'
    post 'buy', to: 'transactions#new'
    # resources :transactions
  end
  devise_for :traders
  resources :traders  
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/trader.rb
class Trader < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
 
  has_many :transactions

  # test for has_many_through
  # has_many :stocks, through: :transactions

  has_and_belongs_to_many :stocks, join_table: 'stocks_traders'

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :confirmable
  enum role: [:trader, :admin]
  after_initialize :set_default_role, :if => :new_record?
  
  def set_default_role
    self.role ||= :trader
  end

  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :age, presence: true, numericality: { greater_than_or_equal_to: 18 }
  # validates :cash, numericality: { greater_than_or_equal_to: 0 }

  def buy_stock(transaction, stock)
    self.cash = cash - (transaction.volume * transaction.price)
    stock.volume = stock.volume + transaction.volume
  end

  def sell_stock(transaction, stock)
    self.cash = cash + (transaction.volume * transaction.price)
    stock.volume = stock.volume - transaction.volume
  end
end

app/controllers/traders_controller.rb
class TradersController < ApplicationController
    before_action :authenticate_trader!
    before_action :set_trader, only: %i[ show edit update destroy ]
  
    # GET /traders or /traders.json
    def index
      @traders = Trader.all
    end
  
    # GET /traders/1 or /traders/1.json
    def show
    end
  
    # GET /traders/new
    def new
      @trader = Trader.new
    end
  
    # GET /traders/1/edit
    def edit
      
    end
  
    # POST /traders or /traders.json
    def create
      @trader = Trader.new(trader_params)
  
      respond_to do |format|
        if @trader.save
          
          RegistrationConfirmationMailer.with(trader: @trader).confirmation_email.deliver_later
          
          format.html { redirect_to root_path, notice: "Trader was successfully created." }
          format.json { render :show, status: :created, location: @trader }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @trader.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /traders/1 or /traders/1.json
    def update
      respond_to do |format|
        if @trader.update(trader_params)

          if @trader.approved_boolean
            ApprovalMailer.with(trader: @trader).trader_approved.deliver_later
          end

          format.html { redirect_to trader_url(@trader), notice: "Trader was successfully updated." }
          format.json { render :show, status: :ok, location: @trader }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @trader.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /traders/1 or /traders/1.json
    def destroy
      @trader.destroy
  
      respond_to do |format|
        format.html { redirect_to traders_url, notice: "Trader was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  
    def today
      @traders = Trader.all
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_trader
        @trader = Trader.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def trader_params
        params.require(:trader).permit(:email, :password, :role, :admin, :first_name, :last_name, :age, :approved_boolean)
      end
  end
  

app/views/traders/_form.html.erb
<%= form_with(model: trader) do |form| %>
  <% if trader.errors.any? %>
    <div class="error red">
      <h2 class="error"><%= pluralize(trader.errors.count, "error") %> prohibited this trader from being saved:</h2>

      <ul>
        <% trader.errors.each do |error| %>
          <li class="error"><%= error.full_message%></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <div class="field">
    <%= form.label :admin %><br />
    <%= form.label :admin, "Yes", value: "true"  %>
    <%= form.radio_button :admin, true, checked: trader.admin %>
    <%= form.label :admin, "No", value: "false" %>
    <%= form.radio_button :admin, false, checked: !trader.admin %>
    </div>
  </div>

  <div>
    <div class="field">
    <%= form.label :approved_boolean %><br />
    <%= form.label :approved_boolean, "Yes", value: "true"  %>
    <%= form.radio_button :approved_boolean, true, checked: trader.approved_boolean %>
    <%= form.label :approved_boolean, "No", value: "false" %>
    <%= form.radio_button :approved_boolean, false, checked: !trader.approved_boolean %>
    </div>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/traders/_nav.html.erb
<div class="tradersall-nav">
  <div class="top">
    <%= link_to image_tag("/logo3.png"), homepage_path, class:"image" %>
    <div>
      <span class="material-symbols-sharp close">close</span>
    </div>
  </div>
  
  <div class="sidebar">
    <a href="/" >
      <span class="material-symbols-sharp">dashboard</span> 
      <h3>Dashboard</h3>
    </a>
    <a href="/stocks" >
      <span class="material-symbols-sharp">shopping_cart</span>
      <h3>Buy Stocks</h3>
    </a>
    <a href="/portfolio">
      <span class="material-symbols-sharp">account_circle</span>
      <h3>Portfolio</h3>
    </a>
    <a href="/transactions">
      <span class="material-symbols-sharp">point_of_sale</span>
      <h3>Transactions</h3>
    </a>
    <a href="/traders/edit">
      <span class="material-symbols-sharp">settings</span>
      <h3>Settings</h3>
    </a>
    <% if current_trader.admin %>
      <a href="/traders" class="active">
        <span class="material-symbols-sharp">group</span>
        <h3>All Users</h3>
      </a>
    <% end %>
    <a data-turbo-method="delete" class="logout" href="/traders/sign_out">
      <span class="material-symbols-sharp">logout</span>
      <h3>Log Out</h3>
    </a>
  </div>
</div>

app/views/traders/edit.html.erb
<%= render "form", trader: @trader%>

app/views/traders/index.html.erb
<div class="tradersall">
  <%= render 'traders/nav' %>
  <% if current_trader.admin %>
    <div>
        <p>Hello <%= current_trader.first_name %> <%= current_trader.last_name %>! You are an admin.
        <p>There are <%= Trader.count %> in the system.</p>

        <% @traders.each do |trader| %>
          <ul>
            <li>
              <p>
                <strong>ID:</strong>
                <%= trader.id %>
              </p>

              <p>
                <strong>Name:</strong>
                <%= trader.first_name %> <%= trader.last_name %>
              </p>
            </li>
            <%= link_to "Show trader", trader %>
          </ul>
        <% end %>

        <div>
          <p><%= link_to "Pending Traders", pending_path %></p>
          <p><%= link_to "New trader", new_trader_session_path %></p>
        </div>
    </div>
  <% else %>
      <p>Hello <%= current_trader.first_name %> <%= current_trader.last_name %>! You are a basic trader. You cannot access this page.
      <p><%= link_to "Back to Home", root_path %></p>
      <%= link_to "Sign Out", destroy_trader_session_path, 'data-turbo-method': :delete %>
  <%end%>
</div>

app/views/traders/show.html.erb
    <ul>
      
      <li><p><strong>ID: </strong><%= @trader.id%></p></p>
      <p><strong>Email: </strong><%= @trader.email%></p>
      <p><strong>First Name: </strong><%= @trader.first_name%></p>
      <p><strong>Last Name: </strong><%= @trader.last_name%></p>
      <p><strong>Age: </strong><%= @trader.age%></p>
      <p><strong>Admin: </strong><%= @trader.admin%></p>
      <p><strong>Confirmed on: </strong><%= @trader.confirmed_at%></p>
      <p><strong>Approved: </strong><%= @trader.approved_boolean%></p>
      </li>
    </ul>

<div>
  <%= link_to "Edit this trader", edit_trader_path(@trader) %> |
  <%= link_to "Back to traders", traders_path %> | 


  <%= button_to "Destroy this trader", @trader, method: :delete %>
</div>