config/routes.rb
Rails.application.routes.draw do

  unauthenticated :trader do
    root to: 'homepage#index', as: :unauthenticated_root
  end

  authenticated :trader do
    root to: 'dashboard#index', as: :authenticated_root
    get '/homepage' => 'homepage#index', as: :homepage
  end

  devise_scope :trader do
    root to: 'devise/sessions#new'
  end

  resources :transactions
  
  # get 'buy', to: 'transactions#new'
  # post 'buy', to: 'transactions#new'

  get 'search', to: 'search#index' 
  get 'portfolio', to: 'dashboard#portfolio'
  get 'pending', to: 'dashboard#pending'
 
# <<<<<<< HEAD
#   get 'portfolio', to: 'pages#portfolio'
 

#   root 'pages#home'
# =======
  
  
  resources :transactions
  resources :stocks_traders
  resources :stocks do
    get 'buy', to: 'transactions#new'
    post 'buy', to: 'transactions#new'
    # resources :transactions
  end
  devise_for :traders
  resources :traders  
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/stock.rb
class Stock < ApplicationRecord
  
 
  has_many :transactions

  # test for has_many_through
  # has_many :traders, through: :transactions
 
  has_and_belongs_to_many :traders, join_table: 'stocks_traders'


  validates :volume, numericality: { greater_than_or_equal_to: 0 }
  validates :code, uniqueness: true

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: %i[ show edit update destroy ]

  # GET /stocks or /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1 or /stocks/1.json
  def show
    @client = Iex.client
    @test = Stock.find(params[:id])
    @test2 = StocksTrader.find_by(trader_id: current_trader.id)
    @company_stock = @client.quote(@stock.code)
    # @stocks_trader = StocksTrader.new(trader_id: current_trader.id, stock_id: @test.id)
    @portfolio = Portfolio.find_by(trader_id: current_trader.id, stock_id: @stock.id)
    @cash = current_trader.cash
    @stocks_trader = StocksTrader.find_or_create_by(trader_id: current_trader.id, stock_id: @test.id)
    
    # @stocks_trader = StocksTrader.find_or_create_by(params[:id])
    # @stocks_trader = StocksTrader.new

    # respond_to do |format|
    #   if @stocks_trader.save
    #     format.html { redirect_to portfolio_path, notice: "Stock was successfully created." }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @stock.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # GET /stocks/new
  def new
    @stocks_trader = StocksTrader.new
  end

  # GET /stocks/1/edit
  def edit
  
  end

  # POST /stocks or /stocks.json
  def create
    @stocks_trader = StocksTrader.new(stocks_trader_params)

    respond_to do |format|
      if @stocks_trader.save
        format.html { redirect_to stock_url(@stock), notice: "Stock was successfully created." }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1 or /stocks/1.json
  def update
    respond_to do |format|
      if @stocks_trader.update(stocks_trader_params)
        format.html { redirect_to stock_url(@stock), notice: "Stock was successfully updated." }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1 or /stocks/1.json
  def destroy
    @stock.destroy

    respond_to do |format|
      format.html { redirect_to stocks_url, notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stock_params
      params.fetch(:stock, {})
    end

    def stocks_trader_params
      params.fetch(:stocks_trader, {})
    end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_form.html.erb
<%= form_with(model: stock) do |form| %>
  <% if stock.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
        <% stock.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/_nav.html.erb
<div class="stocks-nav">
  <div class="top">
    <%= link_to image_tag("/logo3.png"), homepage_path, class:"image" %>
    <div>
      <span class="material-symbols-sharp close">close</span>
    </div>
  </div>
  
  <div class="sidebar">
    <a href="/" >
      <span class="material-symbols-sharp">dashboard</span> 
      <h3>Dashboard</h3>
    </a>
    <a href="/stocks" class="active">
      <span class="material-symbols-sharp">shopping_cart</span>
      <h3>Buy Stocks</h3>
    </a>
    <a href="/portfolio">
      <span class="material-symbols-sharp">account_circle</span>
      <h3>Portfolio</h3>
    </a>
    <a href="/transactions">
      <span class="material-symbols-sharp">point_of_sale</span>
      <h3>Transactions</h3>
    </a>
    <a href="/traders/edit">
      <span class="material-symbols-sharp">settings</span>
      <h3>Settings</h3>
    </a>
    <% if current_trader.admin %>
      <a href="/traders">
        <span class="material-symbols-sharp">group</span>
        <h3>All Users</h3>
      </a>
    <% end %>
    <a data-turbo-method="delete" class="logout" href="/traders/sign_out">
      <span class="material-symbols-sharp">logout</span>
      <h3>Log Out</h3>
    </a>
  </div>
</div>

app/views/stocks/_show_form.html.erb
<%= form_with(model: stocks_trader) do |form| %>

  <div>
    <%= form.label :trader_id, style: "display: block" %>
    <%= form.number_field :trader_id %>
  </div>

  <div>
    <%= form.label :stock_id, style: "display: block" %>
    <%= form.number_field :stock_id %>
  </div>

  <div>
    <%= form.label :volume, style: "display: block" %>
    <%= form.number_field :volume %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/_stock.html.erb
<div id="<%= dom_id stock %>">
</div>

app/views/stocks/edit.html.erb
<h1>Editing stock</h1>

<%= render "show_form", stocks_trader: @stocks_trader %>

<br>

<div>
  <%= link_to "Show this stock", @stock %> |
  <%= link_to "Back to stocks", stocks_path %>
</div>

app/views/stocks/index.html.erb
<div class="stocks">
  <%= render 'stocks/nav' %>
  <div>
    <h1>Stocks</h1>
    <% if current_trader.approved_boolean %>
      <%= search_form_for(@query, url: search_path, method: :get) do |f| %>
          <%= f.search_field :code_or_name_i_cont_any, placeholder: "Search..." %>
          <%= f.submit "Search!" %>
      <% end %>
      <br />
      <div id="stocks" class="stocks-details">
        <% @stocks.each do |stock| %>
          <% if stock.name != nil %>
            <%= stock.id %>
            <%= stock.code %>
            <%= stock.name %>
            <span>
              <%= link_to "Show this stock", stock %>
            </span>
            <br>
          <% end %>
        <% end %>
      </div>
    <%else%>
      <p>You are not approved to trade.</p>
    <%end%>
    <%# <%= link_to "New stock", new_stock_path %>
  </div>
</div>

app/views/stocks/new.html.erb
<h1>New stock</h1>

<%= render "show_form", stocks_trader: @stocks_trader %>

<br>

<div>
  <%= link_to "Back to stocks", stocks_path %>
</div>

app/views/stocks/show.html.erb
<%# <p style="color: green"><%= notice %>
<div class="stocks">
  <%= render 'stocks/nav' %>
  <div>
    <p><strong>Company ID:</strong> <%= @stock.id%></p>
    <p><strong>Company Name:</strong> <%= @stock.name%></p>
    <p><strong>Company Code:</strong> <%= @stock.code%></p>
    <p><strong>Latest Price:</strong> <%= @company_stock.latest_price%></p>
    <p><strong>Latest Time:</strong> <%= @company_stock.latest_time%></p>
    <p><strong>Change:</strong> <%= @company_stock.change%></p>

    <%= render @stock %>

    <br />
    <p><strong>Cash: </strong><%= @cash %></p>
    <p><strong>Owned: </strong>
      <%if @portfolio != nil %>
        <%= @portfolio.volume%>
      <%else%>
        0
      <%end%>
    </p>

    <p><strong>Trader: </strong><%= current_trader.id%></p>
    <p><strong>Stock ID: </strong><%= @stock.id%></p>
    <%# <%= render "show_form", stocks_trader: @stocks_trader %>
    <%# <%= link_to "Buy or Sell", stock_buy_path(@stock) %> 
    <%= link_to "Buy or Sell", stock_buy_path(@stock) %>

    <div>
      <%# <%= link_to "Edit this stock", edit_stock_path(@stock) %>
      <%= link_to "To all stocks", stocks_path %> | 
      <%= link_to "Back to Home", root_path %>
    </div>
  </div>
</div>