config/routes.rb
Rails.application.routes.draw do

  unauthenticated :trader do
    root to: 'homepage#index', as: :unauthenticated_root
  end

  authenticated :trader do
    root to: 'dashboard#index', as: :authenticated_root
    get '/homepage' => 'homepage#index', as: :homepage
  end

  devise_scope :trader do
    root to: 'devise/sessions#new'
  end

  resources :transactions
  
  # get 'buy', to: 'transactions#new'
  # post 'buy', to: 'transactions#new'

  get 'search', to: 'search#index' 
  get 'portfolio', to: 'dashboard#portfolio'
  get 'pending', to: 'dashboard#pending'
 
# <<<<<<< HEAD
#   get 'portfolio', to: 'pages#portfolio'
 

#   root 'pages#home'
# =======
  
  
  resources :transactions
  resources :stocks_traders
  resources :stocks do
    get 'buy', to: 'transactions#new'
    post 'buy', to: 'transactions#new'
    # resources :transactions
  end
  devise_for :traders
  resources :traders  
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[ show edit update destroy ]
  # before_action :get_stock#, except: %i[create]
  # , except: [:index, :show]

  # GET /transactions or /transactions.json
  def index
    if current_trader.admin
      @transactions = Transaction.all
    else
      @transactions = Transaction.where(trader_id: current_trader.id)
    end
    # @transactions = @stock.transactions
  end

  # GET /transactions/1 or /transactions/1.json
  def show
    # @transaction = Transaction.find(params[:id])
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
    @stock = Stock.find(params[:stock_id])
    @client = Iex.client
    @price = @client.quote(@stock.code).latest_price 
    # @query = Stock.ransack(params[:q])
    # @stocks = @query.result(distinct: true)
    # @stock = Stock.find_by(id: @transaction.stock_id)
    # @transaction = @stock.transactions.build

    # @stock = Stock.find_by(id: '1')
    # @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions or /transactions.json
  def create
    # debugger
    @transaction = Transaction.new(transaction_params)

    if Portfolio.exists?(trader_id: current_trader.id, stock_id: @transaction.stock_id)
      @portfolio = Portfolio.find_by(trader_id: current_trader.id, stock_id: @transaction.stock_id)
      # if @transaction.transaction_type  
      #   @portfolio.volume = @portfolio.volume + @transaction.volume
      #   @portfolio.save
      # else
      #   @portfolio.volume = @portfolio.volume - @transaction.volume
      #   @portfolio.save
      # end
    else  
      @portfolio = Portfolio.create(trader_id: current_trader.id, stock_id: @transaction.stock_id, volume: @transaction.volume)
    end

    # @stock = Stock.find_by(id: @transaction.stock_id)
    # # @stock.volume = @stock.volume + @transaction.volume
    # # @stock.save
    
    # # @transaction = @stock.transactions.build(transaction_params)
    # # debugger
    # current_trader.stocks << @stock
    # @current_stock = current_trader.stocks.find_by(id: @transaction.stock_id)
    # @current_stock.volume = @current_stock.volume + @transaction.volume
    # @current_stock.save
    # # debugger
    # if StocksTrader.exists?(stock_id: @transaction.stock_id, trader_id: current_trader.id ) #&& StocksTrader.has_key?(:volume) 
    #   @stocks_trader = StocksTrader.find_by(stock_id: @transaction.stock_id, trader_id: current_trader.id)
    #   @stocks_trader.set_volume(@stock)
    #   # @sum = @stocks_trader.volume.to_i + @transaction.volume.to_i
    #   # @stocks_trader.volume << @sum
    #   # @stocks_trader.save
    #   # debugger
    # else
    #   StocksTrader.create(stock_id: @transaction.stock_id, trader_id: @transaction.trader_id, volume: @transaction.volume)
    #   # debugger
    # end

    respond_to do |format|
      if @transaction.save
        # debugger
        #buy and sell
        if @transaction.transaction_type == true
          if (@transaction.volume * @transaction.price.to_i) <= current_trader.cash

            current_trader.buy_stock(@transaction, StocksTrader.find_by(stock_id: @transaction.stock_id))
            @portfolio.volume = @portfolio.volume + @transaction.volume
            @portfolio.save

            format.html { redirect_to transaction_url(@transaction), notice: "Transaction was successfully created." }
            format.json { render :show, status: :created, location: @transaction }

          else
            # format.html { redirect_to transaction_url(@transaction), notice: "Not enough cash." }
            # format.html { render :new, status: :unprocessable_entity }
            # format.json { render json: @transaction.errors, status: :unprocessable_entity }
          end
        elsif @transaction.transaction_type == false
          if @transaction.volume.to_i <= Portfolio.find_by(trader_id: current_trader.id, stock_id: @transaction.stock_id).volume.to_i 
            
            current_trader.sell_stock(@transaction, StocksTrader.find_by(stock_id: @transaction.stock_id))
            format.html { redirect_to transaction_url(@transaction), notice: "Transaction was successfully created." }
            format.json { render :show, status: :created, location: @transaction }

            @portfolio.volume = @portfolio.volume - @transaction.volume
            @portfolio.save
          # puts @transaction_type
          else
          end
        end

        current_trader.save

        
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transaction_url(@transaction), notice: "Transaction was successfully updated." }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url, notice: "Transaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def buy
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    # def get_stock
      # @stock = Stock.find(params[:stock_id])
    # end

    def set_transaction
      @transaction = Transaction.find(params[:id])
      # @transaction = @stock.transactions.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:transaction).permit(:price, :volume, :trader_id, :stock_id, :transaction_type, :transaction_id)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |form| %>
  <% if transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price, value: @price, :readonly => true %>
  </div>

  <div>
    <%= form.label :volume, style: "display: block" %>
    <%= form.number_field :volume, value: 0 %>
  </div>

  <div>
    <%= form.label :trader_id, style: "display: block" %>
    <%= form.number_field :trader_id, value: current_trader.id, :readonly => true %>
  </div>

  <div>
    <%= form.label :stock_id, style: "display: block" %>
    <%= form.number_field :stock_id, value: @stock.id, :readonly => true %>
  </div>

  <div>
    <div class="field">
    <%= form.label :transaction_type %><br />
    <%= form.label :transaction_type, "Buy", value: "true"  %>
    <%= form.radio_button :transaction_type, true, checked: transaction.transaction_type %>
    <%= form.label :transaction_type, "Sell", value: "false" %>
    <%= form.radio_button :transaction_type, false, checked: !transaction.transaction_type %>
    </div>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/_nav.html.erb
<div class="transactions-nav">
  <div class="top">
    <%= link_to image_tag("/logo3.png"), homepage_path, class:"image" %>
    <div>
      <span class="material-symbols-sharp close">close</span>
    </div>
  </div>
  
  <div class="sidebar">
    <a href="/" >
      <span class="material-symbols-sharp">dashboard</span> 
      <h3>Dashboard</h3>
    </a>
    <a href="/stocks" >
      <span class="material-symbols-sharp">shopping_cart</span>
      <h3>Buy Stocks</h3>
    </a>
    <a href="/portfolio">
      <span class="material-symbols-sharp">account_circle</span>
      <h3>Portfolio</h3>
    </a>
    <a href="/transactions" class="active">
      <span class="material-symbols-sharp">point_of_sale</span>
      <h3>Transactions</h3>
    </a>
    <a href="/traders/edit">
      <span class="material-symbols-sharp">settings</span>
      <h3>Settings</h3>
    </a>
    <% if current_trader.admin %>
      <a href="/traders">
        <span class="material-symbols-sharp">group</span>
        <h3>All Users</h3>
      </a>
    <% end %>
    <a data-turbo-method="delete" class="logout" href="/traders/sign_out">
      <span class="material-symbols-sharp">logout</span>
      <h3>Log Out</h3>
    </a>
  </div>
</div>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>">
  <p>
    <strong>Price:</strong>
    <%= transaction.price %>
  </p>

  <p>
    <strong>Total Shares:</strong>
    <%= transaction.volume %>
  </p>

  <p>
    <strong>Trader ID:</strong>
    <%= transaction.trader_id %>
    <%# <%= Trader.find(transaction.trader_id).first_name %>
    <%# <%= Trader.find(transaction.trader_id).last_name %>  
  </p>

  <p>
    <strong>Company:</strong>
    <% if Stock.find(transaction.stock_id).name == nil %>
      <span>No Company Name</span>
    <% else %>
      <%= Stock.find(transaction.stock_id).name %>
    <% end %>
  </p>

  <p>
    <strong>Type:</strong>
    <% if transaction.transaction_type %>
      Buy
    <% else %>
      Sell
    <% end %>
  </p>

</div>

app/views/transactions/buy.html.erb
<%= current_trader.cash%>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Show this transaction", @transaction %> |
  <%= link_to "Back to transactions", transactions_path %>
</div>

app/views/transactions/index.html.erb
<div class="transactions">
    <%= render 'transactions/nav' %>
    <div>
      <p style="color: green"><%= notice %></p>

      <h1><%= current_trader.admin ? "Users Transaction" : "Transactions" %></h1>

      <div id="transactions">
        <% @transactions.each do |transaction| %>
          <p>Created At: <%= transaction.created_at %></p>
          <%= render transaction %>
          <br/>
        <% end %>
      </div>

      <%# <%= link_to "New transaction", new_transaction_path %>
    </div>
</div>

app/views/transactions/new.html.erb
<div class="stocks">
  <%= render 'stocks/nav' %>
  <div>
    <h1>New transaction</h1>
    <strong><%= @stock.name %><br/></strong>
    <strong><%= @stock.code %></strong>
    <br/><%= current_trader.cash%>
    <br/>
    <%= render "form", transaction: @transaction %>

    <div>
      <%= link_to "Back to Stock", stock_path(params[:stock_id]) %>
    </div>
  </div>
</div>

app/views/transactions/show.html.erb
<div class="transactions">
  <%= render 'transactions/nav' %>
  <div>
    <p style="color: green"><%= notice %></p>

    <%= render @transaction %>

    <div>
    <%# <%= link_to "Edit this transaction", edit_transaction_path(@transaction) %>
    <%= link_to "To Transactions List", transactions_path %>

    <%# <%= button_to "Destroy this transaction", @transaction, method: :delete %>
    </div>
  </div>
</div>